### PR TITLE
Add models

### PR DESCRIPTION
**Pull request by ketphan02**
- Added interface (base model)
- Added PullRequest model
- Added Repository model
- Added Commit model
- Added User model
- Removed sample json
- Restructured how we write tests
- Added test mocks
- Added tests

### CODE REVIEW

**Comment by ketphan02** [comment]
TODO: Update tests

**Comment by ketphan02** [comment]
TODO: Add serializers

**Review by apinchbeck — CHANGES_REQUESTED** [review]
Almost all of these files need documentation. If you'd like, maybe I can help out with this?

**Review by bohuie — APPROVED** [review]
structure looks good

**Pull request merged**
